# Generated by Django 3.2.6 on 2023-08-16 02:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import reserva.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nombre del laboratorio')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('crm', models.CharField(max_length=200, verbose_name='Nombre del responsable CRM')),
                ('telefone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="El número debe estar en este formato::                     '+593 999999999'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefono')),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Laboratorios', to='reserva.especialidade')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(help_text='Ingrese una fecha para la agenda', validators=[reserva.models.validar_dia])),
                ('horario', models.CharField(choices=[('1', '07:00 a 08:00'), ('2', '08:00 a 09:00'), ('3', '09:00 a 10:00'), ('4', '10:00 a 11:00'), ('5', '11:00 a 12:00'), ('6', '12:00 a 13:00'), ('7', '13:00 a 14:00'), ('8', '14:00 a 15:00'), ('9', '15:00 a 16:00'), ('10', '16:00 a 17:00'), ('11', '17:00 a 18:00')], max_length=10)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='reserva.medico')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'unique_together': {('horario', 'dia')},
            },
        ),
    ]
