# Generated by Django 3.2.6 on 2023-08-16 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medico',
            new_name='Laboratorios',
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='medico',
            new_name='laboratorio',
        ),
    ]
